### PR TITLE
Updated 

### PR DESCRIPTION
**Pull request by pratikagr**
_Cards UI changed.
-Added a search bar.

### CODE REVIEW

**Comment by Harishwarrior** [comment]
Screenshot?

**Comment by pratikagr** [comment]
> Screenshot?

Screenshot 2022-10-12 000817

**Comment by Harishwarrior** [comment]
> > Screenshot?
> 
> Screenshot 2022-10-12 000817
> 

The search should be in appbar right?

**Comment by pratikagr** [comment]
Screenshot 2022-10-12 112559
Screenshot 2022-10-12 112614

**Comment by Harishwarrior** [comment]
Search works?

**Comment by pratikagr** [comment]
> Search works?

no this is not functional yet
i cant do the functional part

**Pull request closed without merging**
