### PR TITLE
upgrade: UI Design of app

### PR DESCRIPTION
**Pull request by cynthiakonar**

### CODE REVIEW

**Comment by cynthiakonar** [comment]
This is the new UI - 
image

**Comment by Harishwarrior** [comment]
https://youtu.be/IOyq-eTRhvo

Seperate as widgets not functions.

**Review by Harishwarrior — CHANGES_REQUESTED** [review]
Seperate code as widgets not helper functions.

https://youtu.be/IOyq-eTRhvo

**Comment by Harishwarrior** [comment]
Can you change the app bar color to white and remove elevation.? and create a new PR

**Comment by cynthiakonar** [comment]
sure

**Pull request merged**
